INSERT OR IGNORE INTO resources (
  slug, title, category, description, content_summary, suitable_users, tags,
  file_type, file_size, author, cover_image, related_slugs, quark_url,
  status, sort_order, view_count, click_count, created_at, updated_at
) VALUES
(
  'xiaohongshu-title-templates',
  '小红书标题模板 100 条',
  '自媒体运营',
  '适合图文号和内容新手使用的标题模板，方便快速改写。',
  '["爆款标题结构","常用开头模板","情绪型标题示例","标题避坑清单"]',
  '["小红书新手","图文创作者","自媒体运营","副业尝试者"]',
  '["小红书","标题","自媒体"]',
  'PDF',
  '3.5 MB',
  '小明资料铺',
  '/assets/icon-wish-clean.svg',
  '["ai-video-script-template","side-project-record-sheet","prompt-starter-handbook"]',
  'https://pan.quark.cn/s/5cbe470eb035',
  'published',
  100,
  771,
  288,
  '2026-05-07',
  '2026-05-07'
),
(
  'ai-video-script-template',
  'AI 短视频脚本模板',
  '自媒体运营',
  '整理短视频开头、转折、分镜和口播结构，适合快速起草脚本。',
  '["短视频脚本结构","口播模板","分镜拆解","选题复用清单"]',
  '["短视频创作者","内容运营","AI 内容创作者"]',
  '["短视频","脚本","AI"]',
  'DOCX',
  '4.1 MB',
  '小明资料铺',
  '/assets/icon-wish-clean.svg',
  '["xiaohongshu-title-templates","prompt-starter-handbook","midjourney-starter-guide"]',
  'https://pan.quark.cn/s/5cbe470eb035',
  'published',
  90,
  698,
  245,
  '2026-05-07',
  '2026-05-07'
),
(
  'prompt-starter-handbook',
  'Prompt 入门手册',
  'AI 学习资料',
  '面向新手的提示词写法清单，包含常用结构、改写方式和简单示例。',
  '["提示词基础结构","常用改写方式","场景化示例","检查清单"]',
  '["AI 新手","内容创作者","办公提效用户"]',
  '["Prompt","AI","提示词"]',
  'PDF',
  '5.4 MB',
  '小明资料铺',
  '/assets/icon-ai-clean.svg',
  '["midjourney-starter-guide","ai-tools-directory","ai-video-script-template"]',
  'https://pan.quark.cn/s/5cbe470eb035',
  'published',
  80,
  516,
  188,
  '2026-05-11',
  '2026-05-11'
),
(
  'office-ppt-templates',
  '简约商务风 PPT 模板合集',
  '办公模板',
  '适合汇报、复盘、述职和方案展示的简约商务模板，开箱即可改内容。',
  '["多套版式组合","目录和过渡页齐全","图表页可替换","适合职场汇报"]',
  '["职场新人","项目经理","运营同学"]',
  '["PPT","办公模板","汇报"]',
  'PPTX',
  '21.3 MB',
  '小明资料铺',
  '/assets/icon-report-clean.svg',
  '["excel-functions-cheatsheet","work-review-template","side-project-record-sheet"]',
  'https://pan.quark.cn/s/5cbe470eb035',
  'published',
  70,
  452,
  177,
  '2026-05-12',
  '2026-05-12'
);
